version: "3.9"

services:
  zeph-miner:
    image: xmrig-zephyr
    container_name: zephyr-miner
    restart: unless-stopped
    privileged: true
    env_file: .env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
