version: "3.8"

services:
  rvn-miner:
    image: ravecoin-miner
    container_name: ravecoin-miner
    restart: unless-stopped
    runtime: nvidia
    env_file:
      - .env
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    entrypoint: >
      sh -c "/kawpowminer/linux-ubuntu20-cuda11-1.2.4/kawpowminer -U -P ${RVN_POOL}/${RVN_WALLET_ADDRESS}.${HOSTNAME}"
    expose:
      - "3333"
